spring:
   mvc:
      view:
        prefix: /
        suffix: .html
      resources:
          static-locations: classpath:/static/
   datasource:
      name: mydata
      url: jdbc:mysql://127.0.0.1:3306/education?serverTimezone=GMT
      username: root
      password: root
       # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      #初始化连接池，最小，最大连接数
      initialSize : 2
      minIdle: 2
      maxActive: 20 
      #最大连接时间
      maxWait: 60000
      #间隔多久进行一次检测，检测需要关闭的控线连接
      timeBetweenEvictionRunsMillis: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      #打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
   #redis配置
   redis:
      #Redis数据库索引
      database: 0
      host: 127.0.0.1
      port: 6379
      password: xuefeng4080
      jedis:
         pool:
            #连接池最大连接数(使用负值表示没有限制)
            max-active: 8
            #联机最大阻塞等待时间(使用负值表示没有限制)
            max-wait: -1
            #连接池中的最大控线连接
            max-idle: 5
            #连接池中的最小空闲连接
            min-idle: 0
         #连接超时时间
      timeout: 10000
   #热部署
   devtools:
      restart:
         enabled: false
         additional-paths: src/main/java/**
         exclude: classpath:/static/**
## 该配置节点为独立的节点，容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/**/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  configuration:
     map-underscore-to-camel-case: true #数据库下划线转峰驼命名法
  #type-aliases-package: com.education.bean.basic  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
   offsetAsPageNum: true
   rowBoundsWithCount: true
   pageSizeZero: true
   reasonable: false
   params: 
      pageNum: pageHelperStart
      pageSize: pageHelperRows;
   supportMethodsArguments: false

logging:
  level:
     com:
        bibiboy:
           mapper: debug